require 'plist'

credentials = read_json(
  json_path: 'credentials.json'
)
app = read_json(
  json_path: 'app.json'
)
app_path = File.expand_path('..')

platform :ios do  
  desc "Build iOS"
  lane :build do    
    begin      
      project = File.basename(
        Dir.glob("#{app_path}/ios/*.xcworkspace").first,
        '.xcworkspace'
      )
      keychain_name = 'fastlane-build-today'
      keychain_password = ''

      copy_artifacts(
        target_path: 'ios',
        artifacts: ['GoogleService-Info.plist']
      )      
  
      create_keychain(
        name: keychain_name,
        password: keychain_password,
        unlock: true,    
        default_keychain: true,
        add_to_search_list: true,
        timeout: 0
      )
      
      import_certificate(
        certificate_path: credentials[:ios][:distributionCertificate][:path],
        certificate_password: credentials[:ios][:distributionCertificate][:password],
        keychain_name: keychain_name,      
        keychain_password: keychain_password,
        log_output: true
      )

      profile_path = install_provisioning_profile(
        path: credentials[:ios][:provisioningProfilePath],      
      )
      profile_uuid = File.basename(
        profile_path,
        '.mobileprovision'
      )
      
      update_code_signing_settings(
        use_automatic_signing: false,
        path: "ios/#{project}.xcodeproj",
        code_sign_identity: "iPhone Distribution",
        sdk: "iphoneos*",
        profile_uuid: profile_uuid
      )

      gym(
        clean: true,
        configuration: 'Release',
        scheme: project,
        workspace: "ios/#{project}.xcworkspace",
        export_method: 'ad-hoc',
        export_options: {
          signingStyle: 'manual',
        },
        output_directory: app_path,
        output_name: 'release.ipa'
      )

      delete_keychain(
        name: keychain_name
      )
    end    
  end
end
